apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationskicontainer
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stationskicontainer
  template:
    metadata:
      labels:
        app: stationskicontainer
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:          command:
            - sh
            - -c
            - until nc -z mysql-service 3306; do echo waiting for mysql; sleep 3; done
      containers:
        - name: stationskicontainer
          image: leila1312/stationski:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: stationskicontainer
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 32639
